### ISSUE TITLE
`defaultRichTextElements` methods only allow `string | string[]` return type

### ISSUE THREAD

**Issue by lvl-mattwells** [the-cookbook/solid-intl#1]
Hi! Playing around with this package as I've used `react-intl` quite a bit and would love to use it in Solid.

I'm trying to configure `defaultRichTextElements` to format translated messages, but I'm getting a type error that the result must return a `string | string[]` which I feel like would kind of defeat the purpose. 
![image](https://user-images.githubusercontent.com/92868767/211367114-6f9da026-81af-4e6b-9712-1a4769f5ff53.png)

Digging into the types it looks like `ResolvedIntlConfig` comes with a generic that defaults to `string` which is used in `FormatXMLElementFn` for `defaultRichTextElements`.
![image](https://user-images.githubusercontent.com/92868767/211367322-15186986-3f40-4934-8f56-34009a2e6a61.png)

I see you export `ResolvedIntlConfig` without the generic type specified.
https://github.com/the-cookbook/solid-intl/blob/a675ae53ab203bb20e88d6c0bbb834a900323f1e/src/types.ts#L3-L4

Should this instead be?:
```ts
type IntlConfig = Partial<Omit<ResolvedIntlConfig<JSXElement>, "locale" | "messages">> &
  Required<Pick<ResolvedIntlConfig<JSXElement>, "locale" | "messages">>;
```
I _think_ this also aligns with the `react-intl` implementation:
https://github.com/formatjs/formatjs/blob/649a386f4437cdb0edb0f7d894d56c7a629e9f37/packages/react-intl/src/types.ts#L19-L23

Thoughts on this? If you agree I can put together a PR. Thanks!

**Comment by lvl-mattwells** [comment]
It looks like even bypassing the type still doesn't transform the message. I think it's because we're missing `defaultRichTextElements` in the `process-config` function:
https://github.com/the-cookbook/solid-intl/blob/a675ae53ab203bb20e88d6c0bbb834a900323f1e/src/process-config.ts#L6-L18

**Comment by themgoncalves** [comment]
Hey @lvl-mattwells thanks for the report! It was indeed a fault mine this "short interface" with missing type. I will be reviewing your PR by tomorrow and once merged, deploy a new npm package with the fix
